esphome:
  name: rotary_encoder_set_brightness_simple
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.25
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:
  level: DEBUG

api:

ota:

sensor:
  #******************************************************************************
  # Rotary encoder
  # ESPHome docs: https://esphome.io/components/sensor/rotary_encoder.html
  #******************************************************************************
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: knob
    pin_a: GPIO2
    pin_b: GPIO4
    resolution: 2
    min_value: 0
    max_value: 100
    filters:
      - debounce: 50ms # debounce the encoder wafers
      - throttle: 100ms # limit updates if the user twists the encoder too fast :D
    on_value:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id: light.lounge_table_lamp
              brightness_pct: !lambda 'return x;'

